'use strict';
const dialog=document.querySelector('#conversation-dialog'),form=document.querySelector('#conversation-form');
const steps=[...document.querySelectorAll('.conversation-step')],next=document.querySelector('#conversation-next'),back=document.querySelector('#conversation-back'),error=document.querySelector('#conversation-error'),complete=document.querySelector('#conversation-complete'),phone=document.querySelector('#mobile');
const config=window.COURSE_ENQUIRY_CONFIG||{mode:'preview'},liveMode=config.mode==='live';
const event=(name,extra)=>window.courseEvent?.(name,extra);
let current=0,attempts=0,opener=null,busy=false,challenge=null,verifiedPhone='',receipt=null,leadToken=null,receiptPhone='',lastSend=0;
const initialGoal=document.querySelector('#question-5');
async function api(route,data){const base=new URL(config.apiBase||'/wp-json/tlit-dm/v1',location.origin);if(base.origin!==location.origin)throw new Error('The enquiry service must use this site’s secure connection.');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),25000);try{const r=await fetch(base.href.replace(/\/$/,'')+'/'+route,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(data),signal:controller.signal});let result;try{result=await r.json();}catch{throw new Error('The service is unavailable. Please try again.');}if(!r.ok||!result.success)throw new Error(result.message||'Could not complete your request. Please try again.');return result;}finally{clearTimeout(timer);}}
function setBusy(value){busy=value;next.disabled=value;back.disabled=value||current===0;document.querySelector('#resend-code').disabled=value;form.setAttribute('aria-busy',String(value));}
const originalQuestions=steps.map(step=>step.querySelector('legend').textContent);
function personalise(){const first=document.querySelector('#full-name').value.trim().split(/\s+/)[0].slice(0,35);const prompts={1:'what number can we reach you on?',2:'where can we email your demo details?',3:'would you like marketing tips by email?',4:'where are you in your journey?',5:'what would you like to work towards?',6:'when would you like to start learning?',7:'what would you like to know about the course?',8:'when is a call convenient for you?',9:'let’s verify your phone number.'};steps.forEach((step,i)=>{step.querySelector('legend').textContent=first&&prompts[i]?first+', '+prompts[i]:originalQuestions[i];});}
function render(focus=true){personalise();steps.forEach((step,i)=>{step.hidden=i!==current;step.disabled=i!==current;});back.disabled=current===0||busy;next.disabled=busy||(current===9&&attempts>=5);next.textContent=current===9?'Verify & request my demo →':current===8&&liveMode?'Send verification code →':'Continue →';document.querySelector('#conversation-count').textContent=`Step ${current+1} of ${steps.length}`;document.querySelector('#conversation-progress').value=current;error.textContent='';if(current===9)document.querySelector('#otp-recipient').textContent=(liveMode?'Code sent to ':'Preview for ')+'+91 ••••••'+phone.value.slice(-4);if(focus){const heading=steps[current].querySelector('legend');heading.tabIndex=-1;heading.focus();}}
function openConversation(e){e.preventDefault();opener=e.currentTarget;dialog.showModal();document.body.classList.add('conversation-open');event('demo_open');window.courseTracking?.startGeo();if(complete.hidden)render();else document.querySelector('#restart').focus();}
document.querySelectorAll('[data-enquire]').forEach(b=>b.addEventListener('click',openConversation));
document.querySelector('#close-conversation').addEventListener('click',()=>dialog.close());document.querySelector('#finish-conversation').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{document.body.classList.remove('conversation-open');opener?.focus({preventScroll:true});});
phone.addEventListener('input',()=>phone.setCustomValidity(''));
function normalizedPhone(){let n=phone.value.replace(/[^0-9]/g,'');if(n.length===12&&n.startsWith('91'))n=n.slice(2);const ok=/^[+0-9 ()-]+$/.test(phone.value)&&/^[6-9][0-9]{9}$/.test(n);phone.setCustomValidity(ok?'':'Enter a valid 10-digit Indian mobile number.');if(ok)phone.value=n;return ok;}
function finish(result){receipt=result?.receipt||null;leadToken=result?.leadToken||null;receiptPhone=phone.value;form.hidden=true;complete.hidden=false;document.querySelector('#conversation-count').textContent=liveMode?'Request received':'Preview complete';document.querySelector('#conversation-progress').value=steps.length;if(liveMode){complete.querySelector('.eyebrow').textContent='REQUEST RECEIVED';complete.querySelector('h2').textContent='Your next step is a conversation.';complete.querySelector('h2+p').textContent='Your verified request has reached the course team. They will contact you to arrange the demo date, time and joining details. Reference: '+receipt;const a=complete.querySelector('a[href="thank-you.html"]');if(a)a.href='thank-you.html?status=requested';}event(liveMode?'lead_submitted':'preview_complete',{receipt});document.querySelector('#restart').focus();}
form.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;if(current===1)normalizedPhone();if(!form.reportValidity())return;
 if(current===8&&liveMode){try{setBusy(true);if(!challenge||verifiedPhone!==phone.value){const r=await api('send-otp',{phone:phone.value,name:document.querySelector('#full-name').value});challenge=r.challenge;verifiedPhone=phone.value;lastSend=Date.now();attempts=0;event('otp_requested');}current++;setBusy(false);render();}catch(err){setBusy(false);error.textContent=err.name==='AbortError'?'The request timed out. Please try again.':err.message;}return;}
 if(current===9){if(attempts>=5){error.textContent='Request a new code to try again.';return;}if(!liveMode){if(document.querySelector('#otp-code').value!=='1234'){attempts++;next.disabled=attempts>=5;error.textContent=attempts>=5?'Attempt limit reached. Reset the preview code to try again.':'Use preview code 1234. No real SMS was sent.';return;}finish();return;}
  try{setBusy(true);const result=await api('submit',{challenge,phone:phone.value,otp:document.querySelector('#otp-code').value,name:document.querySelector('#full-name').value,email:document.querySelector('#email').value,goal:initialGoal.querySelector(':checked')?.value||'',emailMarketing:document.querySelector('#email-marketing').checked,tracking:window.courseTracking?.collect()||{},details:Object.fromEntries(['student_status','start_timeline','main_question','preferred_call_time'].map(name=>[name,form.querySelector('input[name="'+name+'"]:checked')?.value||'']))});setBusy(false);finish(result);}catch(err){setBusy(false);error.textContent=err.name==='AbortError'?'The request timed out. Please retry with the same code to check your request.':err.message;}return;}
 current++;render();event('form_step',{step:current+1});});
back.addEventListener('click',()=>{if(current>0&&!busy){current--;render();}});
document.querySelector('#resend-code').addEventListener('click',async()=>{if(busy)return;if(liveMode){if(Date.now()-lastSend<30000){error.textContent='Please wait 30 seconds before requesting another code.';return;}try{setBusy(true);const r=await api('send-otp',{phone:phone.value,name:document.querySelector('#full-name').value});challenge=r.challenge;verifiedPhone=phone.value;lastSend=Date.now();setBusy(false);}catch(err){setBusy(false);error.textContent=err.message;return;}}attempts=0;next.disabled=false;document.querySelector('#otp-code').value='';error.textContent=liveMode?'A new code has been sent.':'Preview reset. Use 1234. No SMS was sent.';document.querySelector('#otp-code').focus();});
document.querySelector('#restart').addEventListener('click',()=>{form.reset();phone.setCustomValidity('');current=0;attempts=0;challenge=null;verifiedPhone='';receipt=null;leadToken=null;receiptPhone='';document.querySelector('#followup-form')?.reset();form.hidden=false;complete.hidden=true;render();});
if(liveMode){document.querySelector('#question-9 .question-help').textContent='Enter the four-digit code sent to your phone. It expires after 5 minutes.';document.querySelector('#resend-code').textContent='Send a new code';document.querySelector('.conversation-footer').textContent='Your details are used for your demo enquiry. Marketing emails require your separate permission.';document.querySelectorAll('.form-preview').forEach(p=>p.textContent='Phone verification helps us reach the right person.');document.querySelector('.preview-note')?.remove();}
render(false);
